/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 120. cm
/gate/world/geometry/setYLength 120. cm
/gate/world/geometry/setZLength 120. cm

/gate/world/daughters/name scanner
/gate/world/daughters/insert box
/gate/scanner/geometry/setXLength 30. cm
/gate/scanner/geometry/setYLength 20. cm
/gate/scanner/geometry/setZLength 20. cm
/gate/scanner/placement/setTranslation 0 40 0. cm # put to 40
/gate/scanner/vis/forceWireframe

/gate/world/daughters/name PatientBox
/gate/world/daughters/insert box
/gate/PatientBox/geometry/setXLength 51. cm # check dimensions ... 
/gate/PatientBox/geometry/setYLength 51. cm # check dimensions ...
/gate/PatientBox/geometry/setZLength 31. cm # check dimensions ...
/gate/PatientBox/placement/setTranslation 0 0 0 cm
/gate/PatientBox/placement/setRotationAxis 0 0 1
/gate/PatientBox/placement/setRotationAngle 180 deg # check this
/gate/PatientBox/setMaterial Air
/gate/PatientBox/vis/setVisible 1
/gate/PatientBox/vis/setColor green

/gate/PatientBox/daughters/name patient
/gate/PatientBox/daughters/insert ImageRegionalizedVolume
/gate/patient/geometry/setImage {inputfolder}/{dicomfile}
/gate/patient/geometry/setHUToMaterialFile AttenuationRange.dat
/gate/patient/placement/setTranslation 0 0 0 mm
#/gate/patient/geometry/buildAndDumpDistanceTransfo {dmap}
/gate/patient/geometry/distanceMap {dmap}

#=================#
# Physics			#
#=================#

/gate/geometry/setIonisationPotential Water 78 eV
/gate/physics/addPhysicsList QGSP_BIC_EMY

/gate/physics/Proton/SetCutInRegion world 1 m
/gate/physics/Gamma/SetCutInRegion world 1 m
/gate/physics/Electron/SetCutInRegion world 1 m
/gate/physics/Positron/SetCutInRegion world 1 m

/gate/actor/addActor PhaseSpaceActor psa
/gate/actor/psa/save Output/{inputfolder}/neutronsPMMA_idx{idx}.root
/gate/actor/psa/attachTo PatientBox
/gate/actor/psa/enableProductionProcess true
/gate/actor/psa/enableEkine true
/gate/actor/psa/enableXPosition true
/gate/actor/psa/enableYPosition true
/gate/actor/psa/enableZPosition true
/gate/actor/psa/enableXDirection true
/gate/actor/psa/enableYDirection true
/gate/actor/psa/enableZDirection true
/gate/actor/psa/enableParticleName true
/gate/actor/psa/useVolumeFrame true # True if attaching to volume; false if attaching to world?
/gate/actor/psa/storeOutgoingParticles false
/gate/actor/psa/enableProductionVolume true
/gate/actor/psa/storeSecondaries true
/gate/actor/psa/addFilter particleFilter
/gate/actor/psa/particleFilter/addParticle neutron

/gate/actor/addActor PhaseSpaceActor psaG
/gate/actor/psaG/save Output/{inputfolder}/gammasPMMA_idx{idx}.root
/gate/actor/psaG/attachTo PatientBox
/gate/actor/psaG/enableProductionProcess true
/gate/actor/psaG/enableEkine true
/gate/actor/psaG/enableXPosition true
/gate/actor/psaG/enableYPosition true
/gate/actor/psaG/enableZPosition true
/gate/actor/psaG/enableXDirection true
/gate/actor/psaG/enableYDirection true
/gate/actor/psaG/enableZDirection true
/gate/actor/psaG/enableParticleName true
/gate/actor/psaG/useVolumeFrame true
/gate/actor/psaG/storeOutgoingParticles false
/gate/actor/psaG/enableProductionVolume true
/gate/actor/psaG/storeSecondaries true
/gate/actor/psaG/addFilter particleFilter
/gate/actor/psaG/particleFilter/addParticle gamma

/gate/actor/addActor DoseActor dose
/gate/actor/dose/save Output/{inputfolder}/dose_idx{idx}_{npart}.root
/gate/actor/dose/attachTo PatientBox
/gate/actor/dose/stepHitType random
/gate/actor/dose/setSize 40 40 1 cm
/gate/actor/dose/setResolution 400 400 1
/gate/actor/dose/enableEdep false
/gate/actor/dose/enableUncertaintyEdep false
/gate/actor/dose/enableDose true
/gate/actor/dose/enableDoseToWater false

/gate/actor/addActor ProductionAndStoppingActor range
/gate/actor/range/save Output/{inputfolder}/range_idx{idx}_{npart}.root
/gate/actor/range/attachTo PatientBox
/gate/actor/range/setResolution 400 400 1
/gate/actor/range/stepHitType post
/gate/actor/range/addFilter particleFilter
/gate/actor/range/particleFilter/addParticlePDG 2212

/gate/run/initialize

#=======================#
# ADD PROTON BEAM	#
#=======================#

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy {energy} MeV # was 85 # was 84.595
/gate/source/PBS/setSigmaEnergy 0. MeV
#/gate/source/PBS/setPosition -52.3 -250 3 mm # baseline
#/gate/source/PBS/setPosition -46.9 -250 4.5 mm # baseline week 1
/gate/source/PBS/setPosition {posx} -250 {posz} mm # baseline week 1
/gate/source/PBS/setSigmaX 2 mm # 2 as small as possible
/gate/source/PBS/setSigmaY 2 mm # 2
/gate/source/PBS/setSigmaTheta 2.5 mrad # 2.5
/gate/source/PBS/setSigmaPhi 2.5 mrad # 2.5
/gate/source/PBS/setEllipseXThetaEmittance 10 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 10 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/source/PBS/setRotationAxis 1 0 0
/gate/source/PBS/setRotationAngle 270 deg

/gate/output/root/disable
#/gate/output/root/setRootSinglesFlag 0
#/gate/output/root/setFileName OutputCTLung/tracking_120MeV_idx{idx}

#===============#
# START BEAMS	#
##===============#

/gate/random/setEngineName MersenneTwister
#/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries {npart} # 1e7
/gate/application/start
